import { VideoProject } from "@/types/videos";

export const allVideoProjects: VideoProject[] = [
  /*
  
  {
    id: "rVVeLdouViU",
    video_title: "একজন ফেসবুক ইঞ্জিনিয়ারের রিজিউমি কেমন হয়?",
    video_description: `How to Build Your Perfect Resume: Learn from a FAANG Employee Example! Are you ready to take your career to new heights and secure your dream job at a top tech company? Join us on this exclusive journey inside the mind of a FAANG employee as we unveil the secrets of their perfect resume! In this eye-opening video, you'll discover the exact strategies and tips used by the industry's finest to stand out from the crowd and impress recruiters.`,
    tags: ["Resume Tips", "FAANG Career", "Job Preparation", "Career Advice"],
    cover_image: "rVVeLdouViU",
    publish_date: "2024-08-04",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/rVVeLdouViU?si=LwWPmI4F34mwLNw8",
    project_images: [],
    category: ["Talking Head", "Explainer"],
    duration: "6:32",
    software_used: ["DaVinci Resolve"],
  },
  {
    id: "JSZmQxg3fos",
    video_title: "Mastering DSA for Developers | Last Call to Join",
    video_description:
      "This workshop helps application developers explore DSA through real-world problems, connecting data structures to business challenges and fostering a problem-solving mindset for practical solutions.",
    tags: ["DSA", "Developer Skills", "Problem Solving", "Career Prep"],
    cover_image: "JSZmQxg3fos",
    publish_date: "2024-04-08",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/JSZmQxg3fos?si=NZYmG1g4mZiYx6Eb",
    project_images: [],
    category: ["Talking Head", "Explainer"],
    duration: "10:12",
    software_used: ["Davinci Resolve", "After Effects"],
  },
  {
    id: "ufRtWGd0cXo",
    video_title:
      "Calm Your Nervous System in 60 Seconds with HeartMath Technique | Angela ORR",
    video_description: `Discover the powerful HeartMath technique to calm your nervous system in just 60 seconds! This quick and effective method can help reduce anxiety, stress, and feelings of overwhelm, promoting a sense of relaxation and calmness.`,
    tags: ["Stress Relief", "Mental Health", "Wellness", "HeartMath"],
    cover_image: "ufRtWGd0cXo",
    publish_date: "2025-06-06",
    client_name: "Growthleo",
    client_image: "/companies/growthleo.png",
    client_feedback: "",
    video_link: "https://youtu.be/ufRtWGd0cXo?si=kgVACrMZQ24tUook",
    project_images: [],
    category: ["Talking Head", "Explainer"],
    duration: "7:18",
    software_used: ["Davinci Resolve"],
  },
  {
    id: "7OuSRaIPOds",
    video_title:
      "The Real Reason You Can’t Change (And How to Fix It in 21 Days) | Angela Orr",
    video_description: `You've tried every habit hack, diet, and self-help book—but real change still feels impossible. Why? Because you're trying to change your behavior without changing your identity.`,
    tags: ["Personal Growth", "Habits", "Mindset", "Self-Improvement"],
    cover_image: "7OuSRaIPOds",
    publish_date: "2025-06-20",
    client_name: "Growthleo",
    client_image: "/companies/growthleo.png",
    client_feedback: "",
    video_link: "https://youtu.be/7OuSRaIPOds?si=TYMRxpKAbbjU9edP",
    project_images: [],
    category: ["Talking Head", "Explainer"],
    duration: "8:13",
    software_used: ["Davinci Resolve"],
  },
  {
    id: "esjJzKjx9Fo",
    video_title: "From Stuck to Strong: The Brain Reset You Need | Angela Orr",
    video_description: `Feeling stuck, lost, or like your best years are behind you? You're not alone and you're not too late.`,
    tags: ["Mental Health", "Brain Training", "Transformation", "Wellness"],
    cover_image: "esjJzKjx9Fo",
    publish_date: "2025-07-11",
    client_name: "Growthleo",
    client_image: "/companies/growthleo.png",
    client_feedback: "",
    video_link: "https://youtu.be/esjJzKjx9Fo?si=Z5IOTm-x-RAB018K",
    project_images: [],
    category: ["Talking Head", "Explainer"],
    duration: "7:59",
    software_used: ["Davinci Resolve"],
  },
  {
    id: "Qwwgg_qt5ew",
    video_title: "Apply logic to simplify your conditional problems",
    video_description:
      "Apply logic to simplify your conditional problems. Watch the video to understand how!",
    tags: ["Coding Tips", "Conditional Logic", "Problem Solving", "Shorts"],
    cover_image: "Qwwgg_qt5ew",
    publish_date: "2024-01-16",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/Qwwgg_qt5ew?si=tTSoTUnuVPdjpc7y",
    project_images: [],
    category: ["Shorts", "Motion Graphics", "Explainer"],
    duration: "2:44",
    software_used: ["After Effects"],
  },
  {
    id: "TiZvFO99rpw",
    video_title: "HTTP Request Explained in 1 minute",
    video_description:
      "Every time you visit a website, your browser sends an HTTP request, and the server responds. But how does this process actually work?",
    tags: ["HTTP", "Web Basics", "Networking", "Shorts"],
    cover_image: "TiZvFO99rpw",
    publish_date: "2025-02-27",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/TiZvFO99rpw?si=vUl9yE-xeKhfq8gd",
    project_images: [],
    category: ["Shorts", "Explainer", "Motion Graphics"],
    duration: "1:10",
    software_used: ["After Effects"],
  },
  {
    id: "2esQF01ob78",
    video_title: "API & API Endpoints Explained with Simple Examples",
    video_description:
      "Every time you use an app or website, APIs are working behind the scenes to fetch data. But what exactly is an API, and how do API endpoints work? 🤔 Watch this video to learn with simple examples!",
    tags: ["API", "Web Basics", "Backend", "Shorts"],
    cover_image: "2esQF01ob78",
    publish_date: "2025-03-05",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/2esQF01ob78?si=SRi4j6f8LWlkHpKh",
    project_images: [],
    category: ["Shorts", "Explainer", "Motion Graphics"],
    duration: "1:24",
    software_used: ["After Effects"],
  },
  {
    id: "fH24XyxcfOc",
    video_title: "Granola to Nutritionist - Short 01",
    video_description:
      "",
    tags: ["API", "Granola", "Ecofaming", "Shorts"],
    cover_image: "fH24XyxcfOc",
    publish_date: "2025-03-06",
    client_name: "Eco Farming",
    client_image: "/companies/Ecofarming.png",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/fH24XyxcfOc",
    project_images: [],
    category: ["Shorts", "Promo"],
    duration: "1:11",
    software_used: ["Davinci Resolve", "After Effects"],
  },
  {
    id: "wBrkYeMlh1U",
    video_title: "Granola to Nutritionist - Short 02",
    video_description:
      "",
    tags: ["API", "Granola", "Ecofaming", "Shorts"],
    cover_image: "wBrkYeMlh1U",
    publish_date: "2025-03-06",
    client_name: "Eco Farming",
    client_image: "/companies/Ecofarming.png",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/wBrkYeMlh1U",
    project_images: [],
    category: ["Shorts", "Promo"],
    duration: "1:09",
    software_used: ["Davinci Resolve", "After Effects"],
  },
  {
    id: "A7O_MV3mgsI",
    video_title: "Granola to Nutritionist - Short 03",
    video_description:
      "",
    tags: ["API", "Granola", "Ecofaming", "Shorts"],
    cover_image: "A7O_MV3mgsI",
    publish_date: "2025-03-07",
    client_name: "Eco Farming",
    client_image: "/companies/Ecofarming.png",
    client_feedback: "",
    video_link: "https://www.youtube.com/shorts/A7O_MV3mgsI",
    project_images: [],
    category: ["Shorts", "Promo"],
    duration: "1:21",
    software_used: ["Davinci Resolve", "After Effects"],
  },
  {
    id: "kpJyIq-mvtc",
    video_title: "EduNurture360 কি? | Edu Bridge Academy",
    video_description: "শুরু হয়ে গেছে EduNurture360 এর ২০২৪ সালের ব্যাচ!",
    tags: [
      "Education",
      "Institute Promo",
      "Bangla Voiceover",
      "Brand Awareness",
    ],
    cover_image: "kpJyIq-mvtc",
    publish_date: "2024-02-01",
    client_name: "Edu Bridge Academy",
    client_image: "/companies/edu-bridge-academy.jpg",
    client_feedback: "",
    video_link: "https://youtu.be/kpJyIq-mvtc?si=wdURtwH9HI1FZmOR",
    project_images: [],
    category: ["Promo", "Motion Graphics"],
    duration: "1:28",
    software_used: ["After Effects"],
  },
  {
    id: "w72TzfYIsgU",
    video_title:
      "Bangladesh’s First Flexible Discount for EdTech – Learn Without Limits!",
    video_description: `Bangladesh's First Flexible Discount for EdTech – Learn Without Limits!`,
    tags: ["EdTech", "Product Launch", "Education Innovation", "Motion Promo"],
    cover_image: "w72TzfYIsgU",
    publish_date: "2025-01-19",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/w72TzfYIsgU?si=50Iu8TME6mC4iH8z",
    project_images: [],
    category: ["Promo", "Motion Graphics"],
    duration: "1:29",
    software_used: ["After Effect"],
  },
  {
    id: "Y3lWN7oFkpw",
    video_title: "EcoRevolution Documentary",
    video_description:
      "A compelling documentary exploring environmental sustainability and the revolution towards eco-friendly practices in modern society.",
    tags: ["Environment", "Sustainability", "Green Revolution", "Documentary"],
    cover_image: "Y3lWN7oFkpw",
    publish_date: "2024-04-12",
    client_name: "EcoRevolution",
    client_image: "/companies/eco-revolution.jpg",
    client_feedback: "",
    video_link: "https://youtu.be/Y3lWN7oFkpw",
    project_images: [],
    category: ["Documentary", "Motion Graphics"],
    duration: "3:51",
    software_used: ["After Effects"],
  },
  {
    id: "MCD9uyZT8Y0",
    video_title: "প্রোগ্রামিং এর ফান্ডামেন্টাল শেখা কেন জরুরী?",
    video_description: `ফান্ডামেন্টাল না শিখে কাজ শেখা শুরু করলে কেন সমস্যা হয়—এই ভিডিওতে জানুন।`,
    tags: [
      "Programming Basics",
      "Education",
      "Beginner Tips",
      "Explainer Video",
    ],
    cover_image: "MCD9uyZT8Y0",
    publish_date: "2024-01-19",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback:
      "Fantastic work! Made complex topics easy to understand with great visuals. The explainer video helped our students grasp fundamental concepts much better.",
    video_link: "https://youtu.be/MCD9uyZT8Y0?si=W6HDf429dZo7hSQM",
    project_images: [],
    category: ["Explainer", "Motion Graphics"],
    duration: "2:43",
    software_used: ["Davinci Resolve"],
  },
  {
    id: "i2JZPZ-a_tc",
    video_title: "Business Email Service",
    video_description: `একটি ভুল ইমেইল কনফিগারেশনের কারণে নষ্ট হতে পারে আপনার সবচেয়ে valuable ক্লায়েন্ট ও ব্যবসার সুনাম।`,
    tags: ["Business IT", "Email Setup", "IT Services", "Promo Video"],
    cover_image: "i2JZPZ-a_tc",
    publish_date: "2025-07-23",
    client_name: "Impel IT",
    client_image: "/companies/impel-it.png",
    client_feedback: "",
    video_link: "https://youtu.be/i2JZPZ-a_tc",
    project_images: [],
    category: ["Motion Graphics", "Promo"],
    duration: "1:28",
    software_used: ["After effects"],
  },
  {
    id: "H29MJ6vLbcg",
    video_title: "Stack Learner Brand Intro",
    video_description:
      "Professional brand introduction animation for Stack Learner with modern motion graphics and smooth transitions.",
    tags: [
      "Brand Animation",
      "Logo Reveal",
      "Motion Graphics",
      "Brand Identity",
    ],
    cover_image: "H29MJ6vLbcg",
    publish_date: "2024-04-12",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://youtu.be/H29MJ6vLbcg",
    project_images: [],
    category: ["Motion Graphics"],
    duration: "0:22",
    software_used: ["After Effects"],
  },
  {
    id: "TInQK-60l2A",
    video_title: "Web & E-commerce Store Development",
    video_description: `ওয়েবসাইট হতে হয় ফাস্ট, স্মার্ট, ও ইনটুইটিভ — যাতে বাড়ে ব্যবসার conversion.`,
    tags: ["Web Development", "E-commerce", "Business Website", "Promo"],
    cover_image: "TInQK-60l2A",
    publish_date: "2025-07-24",
    client_name: "Impel IT",
    client_image: "/companies/impel-it.png",
    client_feedback: "",
    video_link: "https://youtu.be/TInQK-60l2A",
    project_images: [],
    category: ["Motion Graphics", "Promo"],
    duration: "1:21",
    software_used: ["After effects"],
  },
  {
    id: "byQmrdAwFK8",
    video_title: "Digital Marketing",
    video_description: `ভিজিটর আসছে, কিন্তু কাস্টমার হচ্ছে না? সমস্যা প্রোডাক্টে না, মার্কেটিং সিস্টেমে।`,
    tags: [
      "Marketing Strategy",
      "Conversion Optimization",
      "Business Growth",
      "Ads",
    ],
    cover_image: "byQmrdAwFK8",
    publish_date: "2025-07-25",
    client_name: "Impel IT",
    client_image: "/companies/impel-it.png",
    client_feedback: "",
    video_link: "https://youtu.be/byQmrdAwFK8",
    project_images: [],
    category: ["Motion Graphics", "Promo"],
    duration: "1:22",
    software_used: ["After effects"],
  },
  {
    id: "M9znCGjupcY",
    video_title: "Cyber Security",
    video_description: `জাস্ট একটা wrong ক্লিক, অথবা unknown  লিংক… আর মুহূর্তেই আপনার বিজনেস হতে পারে সাইবার হ্যাকের এর  শিকার।`,
    tags: [
      "Cyber Security",
      "Protection",
      "Ads",
    ],
    cover_image: "M9znCGjupcY",
    publish_date: "2025-08-01",
    client_name: "Impel IT",
    client_image: "/companies/impel-it.png",
    client_feedback: "",
    video_link: "https://youtu.be/M9znCGjupcY",
    project_images: [],
    category: ["Motion Graphics", "Promo"],
    duration: "1:30",
    software_used: ["After effects"],
  },
  {
    id: "ppcZHepW7ak",
    video_title:
      "The Power of Asking Better Questions | Angela ORR",
    video_description: `Do you often find yourself stuck in a situation where you're not getting the answers you need because you're not asking the right questions?`,
    tags: ["Stress Relief", "Mental Health", "Wellness"],
    cover_image: "ppcZHepW7ak",
    publish_date: "2025-08-02",
    client_name: "Growthleo",
    client_image: "/companies/growthleo.png",
    client_feedback: "",
    video_link: "https://youtu.be/ppcZHepW7ak",
    project_images: [],
    category: ["Talking Head", "Explainer"],
    duration: "8:22",
    software_used: ["Davinci Resolve"],
  },  */


  //------------------------------------------------------------------------------------------------------------------------------------

  {
    id: "CQIgelbnrwU",
    video_title: "Δημήτρης Μιχαηλίδης: Capriccioza Food Review",
    video_description: `Capriccioza! Αυτό το εστιατόριο θα σε ταξιδέψει στην Ιταλία!" "Απολαύστε ένα αυθεντικό food review στο ιταλικό εστιατόριο Capriccioza, όπου δοκιμάζουμε φρεσκοψημένη πίτσα, λαχταριστά ζυμαρικά και παραδοσιακές ιταλικές γεύσεις. Δείτε την προσωπική μας εμπειρία και ανακαλύψτε αν το Capriccioza είναι πραγματικά η καλύτερη επιλογή για ιταλικό φαγητό στην πόλη. Ιδανικό βίντεο για όλους τους λάτρεις της ιταλικής κουζίνας και όσους ψάχνουν το επόμενο αγαπημένο τους στέκι!`,
    tags: [],
    cover_image: "CQIgelbnrwU",
    publish_date: "2025-09-19",
    client_name: "Dimitris Michailidis",
    client_image: "/companies/dimitrismichailidislogo.png",
    client_feedback: "",
    video_link: "https://youtu.be/CQIgelbnrwU?si=AbbBDPjF8mot369C",
    project_images: [],
    category: ["Food"],
    duration: "1:47",
    //software_used: ["Davinci Resolve"],
  },

  {
    id: "7546680709956652310",
    video_title: "Δημήτρης Μιχαηλίδης: Lidl",
    video_description: `Αυγόφετες στον Φούρνο – Η πιο εύκολη συνταγή για το πρωινό σου!Κάνε like άμα σου άρεσε το βίντεο και ακολούθησέ με για περισσότερες εύκολες συνταγές ❤️

Απόλαυση στο φούρνο! 😍🍳 Φρεσκοψημένες αυγοφέτες με αγαπημένα υλικά από τη @Lidl Hellas ιδανικές για πρωινό ή κολατσιό στο σχολείο και στο γραφείο. Θέλεις γεύση και άρωμα που ξεχωρίζει; Δοκίμασέ τες τώρα! ✨  `,
    tags: [],
    cover_image: "https://www.tiktok.com/@dimitris__michailidis/video/7546680709956652310",
    publish_date: "2025-09-05",
    client_name: "Dimitris Michailidis",
    client_image: "/companies/dimitrismichailidislogo.png",
    client_feedback: "",
    video_link: "https://www.tiktok.com/@dimitris__michailidis/video/7546680709956652310",
    project_images: [],
    category: ["Food"],
    duration: "0:55",
    //software_used: ["Davinci Resolve"],
  },

  
{
  id: "7495431764522028310",
  video_title: "Paros Super Trips: Advertisement Video",
  video_description: "Private sunset ride in Paros. Would you do it like this? Tag your travel buddy. #ParosSuperTrips #LuxuryTransfers #GreekIslandLife #ExploreParos #TravelGreece #TravelGoals #ConSantanderConecto",
  tags: [],
  cover_image: "https://www.tiktok.com/@dimitris__michailidis/video/7550391559695387926",
  publish_date: "2025-04-20",
  client_name: "Paros Super Trips",
  client_image: "/companies/parossupertripslogo.png",
  client_feedback: "",
  video_link: "https://www.tiktok.com/@paros.super.trips/video/7495431764522028310",
  project_images: [],
  category: ["Tourism", "Advertisement", "Promotion"],
  duration: "0:38",
  //software_used: ["CapCut"],
},

{
  id: "7525030482887691553",
  video_title: "Fidias Panayiotou: Elon Musk Relation",
  video_description: "Η σχέση μου με τον Ίλον Μασκ",
  tags: [],
  cover_image: "https://www.tiktok.com/@fidiaspanayiotou/video/7525030482887691553",
  publish_date: "2025-07-09",
  client_name: "Fidias Panayiotou",
  client_image: "/companies/fidiaspanayiotoulogo.png",
  client_feedback: "",
  video_link: "https://www.tiktok.com/@fidiaspanayiotou/video/7525030482887691553",
  project_images: [],
  category: ["Politics",],
  duration: "2:58",
},

{
  id: "7514536626547215648",
  video_title: "Fidias Panayiotou: 339 Kidnapped Children",
  video_description: "Τελικά απήγαγαν οι Ρώσοι παιδιά στην Ουκρανία;",
  tags: [],
  cover_image: "https://www.tiktok.com/@fidiaspanayiotou/video/7514536626547215648",
  publish_date: "2025-06-11",
  client_name: "Fidias Panayiotou",
  client_image: "/companies/fidiaspanayiotoulogo.png",
  client_feedback: "",
  video_link: "https://www.tiktok.com/@fidiaspanayiotou/video/7514536626547215648",
  project_images: [],
  category: ["Politics",],
  duration: "5:12",
},

{
  id: "7520307095279914273",
  video_title: "Fidias Panayiotou: Hiring EN",
  video_description: "We're hiring an Accredited Parliamentary Assistant! Link in bio!",
  tags: [],
  cover_image: "https://www.tiktok.com/@fidias_eu_parliament/video/7520307095279914273",
  publish_date: "2025-06-26",
  client_name: "Fidias Panayiotou",
  client_image: "/companies/fidiaseuparliamentlogo.png",
  client_feedback: "",
  video_link: "https://www.tiktok.com/@fidias_eu_parliament/video/7520307095279914273",
  project_images: [],
  category: ["Politics",],
  duration: "1:14",
},

{
  id: "7542191501661539606",
  video_title: "Taz Smash Burgers: Advertisment",
  video_description: "⚠️❗️SUMMER SALE 5 € ❗️⚠️ Enjoy the summer with taste and offer at TAZ ❗️ Single cheeseburger, medium crispy potatoes and soft drink 330ml, only for 5 € The offer is valid for the whole of August in e-food and in our stores outside Mykonos ❗️ The offer is valid for these stores: 📍 Pericleous 2, Maroussi (opposite the electric one) ☎️ Phone: + 30 210 8025002 📍 Perikli Stavrou 3, Athens (Katechaki) ☎️ Phone: + 30 210 6998986 📦 E-food: Taz smash burger #tazsmashburgers#burgerlover#tastethebest#bestburger#bestburgerintown",
  tags: [],
  cover_image: "https://www.tiktok.com/@taz_smash_burgers/video/7542191501661539606",
  publish_date: "2025-08-24",
  client_name: "Taz Smash Burger",
  client_image: "/companies/tazsmashburgerslogo.png",
  client_feedback: "",
  video_link: "https://www.tiktok.com/@taz_smash_burgers/video/7542191501661539606",
  project_images: [],
  category: ["Food",],
  duration: "0:30",
},

{
  id: "7556205170107878678",
  video_title: "Smoke Island Vapes : Advertisement Video",
  video_description: "🚀 Αυτό είναι μόνο η αρχή… Από ένα μικρό μαγαζί στην Κρήτη σε κάτι πολύ μεγαλύτερο. Κάνε follow για να δεις το ταξίδι του Smoke Island 👀 #fyp #viral #business #tiktokgreece",
  tags: [],
  cover_image: "https://www.tiktok.com/@smokeislandvape/video/7556205170107878678",
  publish_date: "2025-10-01",
  client_name: "Smoke Island",
  client_image: "/companies/smokeislandlogo.png",
  client_feedback: "",
  video_link: "https://www.tiktok.com/@smokeislandvape/video/7556205170107878678",
  project_images: [],
  category: ["Advertisement",],
  duration: "1:17",
},

{
  id: "7559201176449862934",
  video_title: "Smoke Island Vapes : Advertisement Video 2",
  video_description: "Είναι τελικά τόσο κακή όσο νομιζουμε; 🤔 #viral #fyp",
  tags: [],
  cover_image: "https://www.tiktok.com/@smokeislandvape/video/7559201176449862934",
  publish_date: "2025-10-09",
  client_name: "Smoke Island",
  client_image: "/companies/smokeislandlogo.png",
  client_feedback: "",
  video_link: "https://www.tiktok.com/@smokeislandvape/video/7559201176449862934",
  project_images: [],
  category: ["Advertisement",],
  duration: "0:52",
},

{
  id: "7556919446271659266",
  video_title: "Rocket Dust: DMO Deejay Crete",
  video_description: "Η Κρήτη δεν θα είναι ποτέ ξανά η ίδια! Χιλιάδες μηχανές, άπειρα χαμόγελα, και μία ενέργεια που δεν περιγράφεται με λόγια. Με τον @DMO γράψαμε ιστορία στο μεγαλύτερο meet up της χρονιάς. 👉 Δες το teaser και νιώσε τον παλμό! #RocketDust #DMO #CreteMeetUp #BikeLife",
  tags: [],
  cover_image: "https://www.tiktok.com/@rocket.dust/video/7556919446271659266",
  publish_date: "2025-10-03",
  client_name: "Rocket Dust",
  client_image: "/companies/rocketdustlogo.png",
  client_feedback: "",
  video_link: "https://www.tiktok.com/@rocket.dust/video/7556919446271659266",
  project_images: [],
  category: ["Action",],
  duration: "1:13",
},

{
  id: "7554445708846386454",
  video_title: "LessDietOfficial: Vitamin D3",
  video_description: "Εσύ ήξερες πόσο σημαντική είναι η Βιταμίνη D3;",
  tags: [],
  cover_image: "https://www.tiktok.com/@lessdietofficial/video/7554445708846386454",
  publish_date: "2025-09-26",
  client_name: "LessDietOfficial",
  client_image: "/companies/lessdietofficial.png",
  client_feedback: "",
  video_link: "https://www.tiktok.com/@lessdietofficial/video/7554445708846386454",
  project_images: [],
  category: ["Health",],
  duration: "0:48",
},

{
  id: "7559215805704129814",
  video_title: "Top Dog: Shampoo Advertisment Video",
  video_description: "Εσύ γνωρίζεις κάθε πότε πρέπει να κάνει μπανάκι ο σκύλος σου ;; 💛 — Με το σωστό σαμπουάν, ο μικρός σου φίλος θα νιώθει και θα μυρίζει υπέροχα! • #TopDog #PetCare #DogGrooming #Dog #Shampoo",
  tags: [],
  cover_image: "https://www.tiktok.com/@topdog_pet_products/video/7559215805704129814",
  publish_date: "2025-10-09",
  client_name: "Top Dog - Natural Pet Products",
  client_image: "/companies/topdoglogo.png",
  client_feedback: "",
  video_link: "https://www.tiktok.com/@topdog_pet_products/video/7559215805704129814",
  project_images: [],
  category: ["Pets",],
  duration: "0:38",
},

{
  id: "7570648601974672662",
  video_title: "Giannelis: Salt Chip Challenge",
  video_description: "Βρήκα γυναίκες στην Αθήνα ! #giannelis #koupi #saltchipchallenge",
  tags: [],
  cover_image: "https://www.tiktok.com/@giannelis_/video/7570648601974672662",
  publish_date: "2025-11-09",
  client_name: "Giannelis",
  client_image: "/companies/giannelislogo.png",
  client_feedback: "",
  video_link: "https://www.tiktok.com/@giannelis_/video/7570648601974672662",
  project_images: [],
  category: ["Challenge",],
  duration: "0:59",
},


{
  id: "7564749402988891395",
  video_title: "Giannelis: Steakhouse Σικελία",
  video_description: "50€ Steak Στην Ταορμινα! #steak #giannelis #koupi #taormina #sicily",
  tags: [],
  cover_image: "https://www.tiktok.com/@giannelis_/video/7564749402988891395",
  publish_date: "2025-10-24",
  client_name: "Giannelis",
  client_image: "/companies/giannelislogo.png",
  client_feedback: "",
  video_link: "https://www.tiktok.com/@giannelis_/video/7564749402988891395",
  project_images: [],
  category: ["Food", "Tourism"],
  duration: "0:59",
},

{
  id: "7559682707261885718",
  video_title: "Giannelis: McDonalds Morocco",
  video_description: "Έφαγα Mac Στο Μαροκο ! #morroco #macdonalds #giannelis #koupi",
  tags: [],
  cover_image: "https://www.tiktok.com/@giannelis_/video/7559682707261885718",
  publish_date: "2025-10-10",
  client_name: "Giannelis",
  client_image: "/companies/giannelislogo.png",
  client_feedback: "",
  video_link: "https://www.tiktok.com/@giannelis_/video/7559682707261885718",
  project_images: [],
  category: ["Food", "Tourism"],
  duration: "0:59",
},

{
  id: "7566389323944201474",
  video_title: "Snobaria: The Travel Crew",
  video_description: "ΜΑΝΤΕΨΤΕ ΤΟΝ ΠΡΟΟΡΙΣΜΟ @Markella Travels✈️🌍🌺 #snobaria",
  tags: [],
  cover_image: "https://www.tiktok.com/@snobaria/video/7566389323944201474",
  publish_date: "2025-10-28",
  client_name: "Snobaria",
  client_image: "/companies/snobarialogo.png",
  client_feedback: "",
  video_link: "https://www.tiktok.com/@snobaria/video/7566389323944201474",
  project_images: [],
  category: ["Advertisement", "Tourism"],
  duration: "1:48",
},

{
  id: "7564097268593216790",
  video_title: "Snobaria: About You Haul",
  video_description: "@aboutyou_gr Κάνε και εσύ την παραγγελία σου μέχρι 26/10 και μπες στην κλήρωση!♥️ ΜΗΝ ΞΕΧΑΣΕΙΣ τον κωδικό 20SNOB για EXTRA 20% έκπτωση ✨",
  tags: [],
  cover_image: "https://www.tiktok.com/@snobaria/video/7564097268593216790",
  publish_date: "2025-10-22",
  client_name: "Snobaria",
  client_image: "/companies/snobarialogo.png",
  client_feedback: "",
  video_link: "https://www.tiktok.com/@snobaria/video/7564097268593216790",
  project_images: [],
  category: ["Advertisement", "Haul"],
  duration: "2:29",
},

{
  id: "AR4nC1nQr4g",
  video_title: "ItsOnlySkillz: Playmobil",
  video_description: "ΕΠΕΣΤΡΕΨΕ Ο HITMAN 2 ΣΤΗΝ ΠΟΛΗ @playmobil.gr #Skytrails #playmobil #playmobilgreece Μην ξεχάσεις να κάνεις LIKE, ΚΟΙΝΟΠΟΙΗΣΗ και ΕΓΓΡΑΦΗ στο κανάλι! ✅ Κάνε εγγραφή για να με βοηθήσεις! ✅ Κάνε ένα LIKE στο βίντεο!✅ Κοινοποίησε το βίντεο!📷 Instagram ➝   / itsonly_skillz  📱TikTok ➝   / itsonly_skillz  📩 Business Inquiries ➝ ItsOnlySkillzOfficial@gmail.com",
  tags: [],
  cover_image: "AR4nC1nQr4g",
  publish_date: "2025-10-09",
  client_name: "ItsOnlySkillz",
  client_image: "/companies/itsonlyskillzlogo.png",
  client_feedback: "",
  video_link: "https://youtu.be/AR4nC1nQr4g?si=XSvbqyutk7eUTzlY&t=29",
  project_images: [],
  category: ["Advertisement",],
  duration: "1:03",
},

{
  id: "7gNm8POM6QI",
  video_title: "ItsOnlySkillz: SufShark VPN",
  video_description: "ΜΕ ΕΒΑΛΑΝ ΣΤΗΝ ΦΥΛΑΚΗ ΤΟΥ ΑΛΚΑΤΡΑΖ (GTA RP) ΚΑΤΕΒΑΣΕ ΤΟ Surfshark εδώ : https://surfshark.com/onlyskillz βάλτε τον κωδικό ONLYSKILLZ στο checkout και θα πάρετε 4 extra μήνες Surfshark VPN! ΣΤΟ ΣΗΜΕΡΙΝΟ GTA RP ΜΕ ΣΤΕΛΝΟΥΝ ΣΤΗ ΘΡΥΛΙΚΗ ΦΥΛΑΚΗ ΤΟΥ ΑΛΚΑΤΡΑΖ. ΦΡΟΥΡΟΙ, ΕΠΙΚΙΝΔΥΝΟΙ ΚΡΑΤΟΥΜΕΝΟΙ ΚΑΙ ΜΥΣΤΙΚΑ ΠΕΡΑΣΜΑΤΑ ΠΟΥ ΔΕΝ ΠΡΕΠΕΙ ΝΑ ΔΩ ΚΑΝΕΙΣ. ΘΑ ΚΑΤΑΦΕΡΩ ΝΑ ΕΠΙΖΗΣΩ; ΘΑ ΑΠΟΔΡΑΣΩ; Ή ΘΑ ΜΕΙΝΩ ΓΙΑ ΠΑΝΤΑ ΣΤΟ ΑΛΚΑΤΡΑΖ; ΔΕΣ ΜΕΧΡΙ ΤΟ ΤΕΛΟΣ ΓΙΑΤΙ ΣΥΜΒΑΙΝΕΙ ΚΑΤΙ ΠΟΥ ΑΛΛΑΖΕΙ ΤΗΝ ΙΣΤΟΡΙΑ ΤΟΥ EMERALD CITY. ΚΑΝΕ LIKE & COMMENT ΑΝ ΘΕΣ ΣΥΝΕΧΕΙΑ ΜΕ ΑΠΟΔΡΑΣΕΙΣ.",
  tags: [],
  cover_image: "7gNm8POM6QI",
  publish_date: "2025-10-13",
  client_name: "ItsOnlySkillz",
  client_image: "/companies/itsonlyskillzlogo.png",
  client_feedback: "",
  video_link: "https://youtu.be/7gNm8POM6QI?si=D5Gc5-Sc0QOq-x3e&t=345",
  project_images: [],
  category: ["Advertisement",],
  duration: "0:44",
},

{
  id: "5mTsyNG1U38",
  video_title: "inPozar: Εστιατόριο Άσσωρος Λουτρά Πόζαρ",
  video_description: "🍷 Άσσωρος Πόζαρ  Εκεί που η γεύση συναντά την απόλαυση! Στην καρδιά της λουτρόπολης των Λουτρών Πόζαρ, ο Άσσωρος σε προσκαλεί σε ένα ταξίδι γεύσεων που δεν ξεχνιέται! Κάθε πιάτο, μια μικρή ιστορία… μαγειρεμένη με μεράκι, φαντασία και τα πιο αγνά υλικά. Από τις παραδοσιακές συνταγές μέχρι τις πιο δημιουργικές προτάσεις, εδώ η κάθε μπουκιά γίνεται εμπειρία! Ζήσε την αυθεντική φιλοξενία, απόλαυσε τα αρώματα, και άσε τη γεύση να σε μαγέψει. #Ασσωρος #ΛουτραΠοζαρ #ΕστιατοριοΑσσωρος #inPozar #GreekFood #TasteOfGreece #Gastronomy #FoodLovers #PozarSprings #VisitPozar #TraditionalCuisine #FoodArt",
  tags: [],
  cover_image: "5mTsyNG1U38",
  publish_date: "2025-10-29",
  client_name: "inPozar “Οδηγός Λουτρών Πόζαρ",
  client_image: "/companies/inPozarlogo.jpg",
  client_feedback: "",
  video_link: "https://youtu.be/5mTsyNG1U38?si=00g2NU52X1u1PjUD",
  project_images: [],
  category: ["Tourism",],
  duration: "1:34",
},

{
  id: "LC0ZEK_muYw",
  video_title: "inPozar: Λουτρά Πόζαρ",
  video_description: "🎬 4 Εποχές – Ένας Προορισμός | Λουτρά Πόζαρ Υπάρχουν μέρη που δεν γνωρίζουν εποχή. Εκεί όπου το νερό κυλά αδιάκοπα, η φύση αλλάζει φορεσιά… κι όμως, η μαγεία μένει ίδια. Τα Λουτρά Πόζαρ δεν είναι απλώς ένας προορισμός — είναι μια εμπειρία που σε ταξιδεύει κάθε στιγμή του χρόνου. 4 Εποχές – Ένας Προορισμός. Λουτρά Πόζαρ. #LoutraPozar #PozarThermalBaths #inPozar #4SeasonsOneDestination #PozarSprings #GreekNature #VisitPozar #TravelGreece #PozarExperience #ThermalWaters #ExploreGreece",
  tags: [],
  cover_image: "LC0ZEK_muYw",
  publish_date: "2025-11-13",
  client_name: "inPozar “Οδηγός Λουτρών Πόζαρ",
  client_image: "/companies/inPozarlogo.jpg",
  client_feedback: "",
  video_link: "https://youtu.be/LC0ZEK_muYw?si=rVskB7chWy4KmqGs",
  project_images: [],
  category: ["Tourism",],
  duration: "0:48",
},



{
  id: "jKeXl7CUP0g",
  video_title: "Studio Pantelidis: Βίντεο Γάμου Γιώργος & Ιωάννα",
  video_description: "",
  tags: [],
  cover_image: "jKeXl7CUP0g",
  publish_date: "2025-11-11",
  client_name: "Studio Pantelidis",
  client_image: "/companies/studiopatelidislogo.jpg",
  client_feedback: "",
  video_link: "https://youtu.be/jKeXl7CUP0g?si=F8x7l9PHuZwvphe6",
  project_images: [],
  category: ["Wedding",],
  duration: "1:35",
},

{
  id: "a8r2VgXw6pg",
  video_title: "Studio Pantelidis: Βίντεο Γάμου Μανώλης & Ειρήνη",
  video_description: "",
  tags: [],
  cover_image: "a8r2VgXw6pg",
  publish_date: "2025-10-16",
  client_name: "Studio Pantelidis",
  client_image: "/companies/studiopatelidislogo.jpg",
  client_feedback: "",
  video_link: "https://youtu.be/a8r2VgXw6pg?si=kRLkOdVMYuyDNPiH",
  project_images: [],
  category: ["Wedding",],
  duration: "2:52",
},





{
  id: "lmSAfFDe2oI",
  video_title: "inPozar: ΛΟΥΤΡΑ ΠΟΖΑΡ",
  video_description: "Τέσσερις εποχές. Ένας προορισμός.Κάθε εποχή, ένα νέο πρόσωπο της φύσης. Κάθε σταγόνα, μια ιστορία που ψιθυρίζει μέσα στους ατμούς των Λουτρών Πόζαρ. 💧 Εδώ ο χειμώνας καίει με τη ζεστασιά του νερού. Η άνοιξη ανθίζει μέσα στον ήχο του ποταμού. Το καλοκαίρι λάμπει κάτω από το φως των βράχων. Και το φθινόπωρο ντύνει τα πάντα με χρυσό. 🍁 Αυτό δεν είναι απλώς ένας τόπος. Είναι μια εμπειρία που σε καλεί να την ζήσεις — ξανά και ξανά. Λουτρά Πόζαρ. Τέσσερις εποχές, ένας προορισμός. 🌿 #LoutraPozar #PozarThermalBaths #FourSeasonsOneDestination #inPozar #PozarExperience #VisitAlmopia #NatureDreams #GreeceAllYear #DiscoverGreece #ThermalEscape #PozarMagic #GreekNature",
  tags: [],
  cover_image: "lmSAfFDe2oI",
  publish_date: "2025-10-15",
  client_name: "inPozar “Οδηγός Λουτρών Πόζαρ",
  client_image: "/companies/inPozarlogo.jpg",
  client_feedback: "",
  video_link: "https://youtu.be/lmSAfFDe2oI?si=rQR1AbODfU1S-XSI",
  project_images: [],
  category: ["Tourism",],
  duration: "2:09",
},



];
